# -*- coding: utf-8 -*-

WINDOW = '#f8f8f8'

TEXT = '#333'
TEXT_DISABLED = '#b0b0b0'
TEXT_MUTED = '#888786'
TEXT_ERROR = '#de6a66'

BORDER_LIGHT = '#d3d3d3'
BORDER_DARK = '#cecece'
BORDER_FOCUS = '#0090f1'

LINE_EDIT = '#fff'
PLAIN_EDIT = '#fff'
COMBOBOX = '#f1f1f1'

BUTTON = '#f1f1f1'
BUTTON_HOVER = '#ececec'
BUTTON_PRESSED = '#dddddd'
BUTTON_DISABLED = '#f1f1f1'
BUTTON_DEFAULT = '#0090f1'
BUTTON_DEFAULT_HOVER = '#0062a3'

SCROLLBAR = '#c1c1c1'
SCROLLBAR_HOVER = '#929292'

SELECTION = '#0060c0'
SELECTION_TEXT = '#fff'

TAB_INACTIVE = WINDOW
TAB_ACTIVE = '#fff'
TAB_ACTIVE_BORDER = '#0090f1'

TRANSLATED_TABLEVIEW = '#fff'
TRANSLATED_TABLEVIEW_ODD = '#f1f1f1'
TRANSLATED_BAR = '#fff'

VALIDATED_TABLEVIEW = '#cecee7'
VALIDATED_TABLEVIEW_ODD = '#c2c2e0'
VALIDATED_BAR = '#c2c2e0'

PROGRESS_TABLEVIEW = '#eccdec'
PROGRESS_TABLEVIEW_ODD = '#e7c1e7'
PROGRESS_BAR = '#e7c1e7'

UNVALIDATED_TABLEVIEW = '#f2c3c2'
UNVALIDATED_TABLEVIEW_ODD = '#eeb4b2'
UNVALIDATED_BAR = '#eeb4b2'

DIFFERENT_TABLEVIEW = '#efd7c4'
DIFFERENT_TABLEVIEW_ODD = '#eaccb5'

PROGRESSBAR = BUTTON_HOVER

EDITOR_LINES = '#f1f1f1'
EDITOR_LINES_TEXT = '#b0b0b0'
EDITOR_LINES_BORDER = None

EDITOR_LINE = WINDOW
EDITOR_BRACKET = BUTTON_PRESSED

EDITOR_SIMNAME = '#388f21'
EDITOR_SIMNAME_BOLD = True

EDITOR_MALE = '#0057ad'
EDITOR_MALE_BOLD = True

EDITOR_FEMALE = '#914c9c'
EDITOR_FEMALE_BOLD = True

EDITOR_VAR_BOLD = True

EDITOR_TAG = TEXT_MUTED

HEADER = '#fff'

FONT_SANS = "Roboto, 'Segoe UI', sans-serif"
FONT_MONOSPACE = "'JetBrains Mono', Consolas, 'Courier New', monospace"
