# -*- coding: utf-8 -*-

APP_VERSION = '1.3.1'
APP_RELEASE_CANDITATE = False
DICTIONARY_VERSION = 4

COLUMN_MAIN_INDEX = 1
COLUMN_MAIN_ID = 2
COLUMN_MAIN_INSTANCE = 3
COLUMN_MAIN_GROUP = 4
COLUMN_MAIN_SOURCE = 5
COLUMN_MAIN_TRANSLATE = 6
COLUMN_MAIN_COMMENT = 7
COLUMN_MAIN_FLAG = 8

COLUMN_DICTIONARIES_PACKAGE = 1
COLUMN_DICTIONARIES_SOURCE = 2
COLUMN_DICTIONARIES_TRANSLATE = 3
COLUMN_DICTIONARIES_LENGTH = 4

RECORD_MAIN_INDEX = 0
RECORD_MAIN_ID = 1
RECORD_MAIN_INSTANCE = 2
RECORD_MAIN_GROUP = 3
RECORD_MAIN_SOURCE = 4
RECORD_MAIN_TRANSLATE = 5
RECORD_MAIN_FLAG = 6
RECORD_MAIN_RESOURCE = 7
RECORD_MAIN_RESOURCE_ORIGINAL = 8
RECORD_MAIN_PACKAGE = 9
RECORD_MAIN_SOURCE_OLD = 10
RECORD_MAIN_TRANSLATE_OLD = 11
RECORD_MAIN_INDEX_ALT = 12
RECORD_MAIN_COMMENT = 13

RECORD_DICTIONARY_PACKAGE = 0
RECORD_DICTIONARY_SOURCE = 1
RECORD_DICTIONARY_TRANSLATE = 2
RECORD_DICTIONARY_LENGTH = 3

FLAG_UNVALIDATED = 0
FLAG_PROGRESS = 1
FLAG_VALIDATED = 2
FLAG_TRANSLATED = 3
FLAG_REPLACED = 4

SEARCH_IN_SOURCE = 0
SEARCH_IN_DESTINATION = 1
SEARCH_IN_ID = 2

NUMERATION_STANDART = 0
NUMERATION_SOURCE = 1
NUMERATION_XML = 2
NUMERATION_XML_DP = 3

EXPORT_STBL = 0
EXPORT_XML = 1
EXPORT_XML_DP = 2
